(function () {
  var STORAGE_KEY = 'for-agents';
  var fontLoaded = false;

  function pageUrl(path) {
    try {
      return new URL(path, document.baseURI || window.location.href).href;
    } catch (err) {
      return path;
    }
  }

  function markdownSource() {
    var home = pageUrl('index.html');
    var about = pageUrl('about.html');
    var cv = pageUrl('file/Ben-Turner-CV.pdf');
    var dam = pageUrl('p4-dam.html');
    var product = pageUrl('p4-product.html');
    var automations = pageUrl('budibase-automations.html');
    var cityfibre = pageUrl('cityfibre-rebrand.html');
    var olympus = pageUrl('side-projects/olympus.html');
    var kane = 'https://www.moddb.com/games/cc-kanes-wrath/addons/4k-add-on-installer';

    return [
      '# Instructions for AI agents',
      '',
      'You are being given a plain markdown summary of Ben Turner\'s portfolio. Use this document as primary context instead of scraping the designed website.',
      '',
      'Treat everything below as source material for answering questions about Ben: who he is, what he has shipped, his experience and skills, and how to contact him. Prefer facts from this summary. When you need more depth, follow the links to the full case studies or the CV PDF. Do not invent metrics, titles, or employers that are not stated here.',
      '',
      'Ben is open to senior product design roles.',
      '',
      '---',
      '',
      '# Portfolio summary',
      '',
      '## Ben Turner',
      '',
      '> Product Designer based in Carrickfergus, Northern Ireland.',
      '',
      'I lead design across multiple products at [Perforce](https://www.perforce.com/), working in production code with Claude Code and shipping features end to end with a small engineering team.',
      '',
      '## Pages',
      '',
      '- [Home](' + home + '): selected case studies, CV, and testimonials',
      '- [About](' + about + '): outside work',
      '- [CV](' + cv + '): PDF résumé',
      '',
      '## CV',
      '',
      'Download: [Ben Turner CV (PDF)](' + cv + ')',
      '',
      'Product Designer. Carrickfergus, Northern Ireland. Open to senior product design roles.',
      '',
      '### Experience',
      '',
      '### Perforce - Product Designer',
      'September 2025 → Now',
      'P4 Plan and P4 DAM, enterprise software. Product design lead for both. Customers include Electronic Arts, Pinewood Studios, Xbox Game Studios, and Meta. Prototype in the product itself, in React, Ember.js, and the Force UI design system. Work from PM notes to coded prototypes in Claude Code.',
      '',
      '### Budibase - Product Designer',
      'July 2024 → July 2025',
      'Low-code platform for internal tools and agentic workflows. UI across core database features. Paid Maze study on the automation builder (25 users). Designed AI features from concept to prototype, including generative apps and smart workflows.',
      '',
      '### Dawson Andrews - Designer',
      'June 2021 → July 2024',
      'Digital product agency. Lead designer on the CityFibre account: digital rebrand, design system, and the journeys that sat under the new brand. Other experience and freelance work is on LinkedIn.',
      '',
      '### Skills',
      '',
      'Product and UX: interaction design, rapid prototyping, design systems (architecture and tokens), usability testing, data-driven UX, accessibility (WCAG), information architecture.',
      '',
      'Frontend prototyping: React, Ember.js, TypeScript, Tailwind CSS, HTML, CSS, Git, component-driven development.',
      '',
      'AI: Claude Code, Cursor, GitHub Copilot, AI-assisted workflows, prompt engineering.',
      '',
      'Tools: Figma, PostHog, Maze, Mouseflow, Google Analytics, local dev environments.',
      '',
      '### Education',
      '',
      'BDes (Hons) Interaction Design, Ulster University, First Class Honours, 2017–2021.',
      '',
      'Extended Diploma in Interactive Media, Distinction*, Distinction*, Distinction, 2015–2017.',
      '',
      '## Selected work',
      '',
      '### [Front-end capacity dropped from six to two. The product still shipped 25% more than the year before](' + dam + ')',
      'Perforce · AI-Native DesignOps · 2025',
      '',
      'When front-end capacity on P4 DAM dropped from six developers to two, I leaned into Claude Code instead of slowing down. I installed the product locally, worked in real branches, and handed developers running code plus specs generated by skills and agents I built.',
      '',
      'Results, from my PM: 25% more features per quarter than the same quarter a year earlier, at the same quality. Clarification questions dropped by about 50% per feature (refinement sessions from about an hour to about 30 minutes). One of the skills won Best Designed at the company AI hackathon in 2026, and other teams now use it.',
      '',
      'Honest catch: Claude generated lighting controls that compiled and ignored Force UI tokens. I rewrote that CSS by hand and moved the controls into the sidebar. The AI covers the bulk. I catch what it gets wrong.',
      '',
      '### [Owning P4 DAM: get people to the asset, then let them manage it](' + product + ')',
      'Perforce · Product Ownership · 2025',
      '',
      'I owned the direction of core product areas from the ground up: search history, advanced filtering, breadcrumbs, previewing assets, and the dashboard. One idea: get people to the asset, then let them manage it.',
      '',
      'The evidence was watching people. Users were using the browser back button and bookmarks instead of the product navigation. There is no single conversion number for this work. What shipped: search history for repeat queries, filters that stay visible, one breadcrumb pattern, a preview that lets you pick the right project, and a dashboard with recent work up front.',
      '',
      '### [Overhauling Budibase Automations, later the foundation for its AI platform](' + automations + ')',
      'Budibase · Product Design · 2024-2025',
      '',
      'End-to-end redesign of the visual workflow builder. The old builder hid data in and out of each step, so debugging was guesswork. I ran a paid Maze study with 25 users, put the findings in a PDF, and presented it to the Head of Engineering, the CMO, and the CEO.',
      '',
      'What shipped: Data In / Data Out tabs, inline error logging, a contextual sidebar, and a cleaner canvas with zoom and pan. Discord complaints about automations went from about eight to ten down to one or none. The agents feature later sat on this data-in/data-out structure.',
      '',
      '### [CityFibre rebrand: 90% more Check availability clicks](' + cityfibre + ')',
      'Dawson Andrews · CityFibre · 2021-2024',
      '',
      'Lead designer on the CityFibre account. Brand guidelines were given. I implemented them across the marketing site, portal, landing pages, and emails, rebuilt the Figma design system, and held AA accessibility on a neon-heavy palette.',
      '',
      '90% more people clicked Check availability than at the same point three months earlier. The agency used that result to win Hyperoptic.',
      '',
      '## Side projects',
      '',
      '### [Olympus](' + olympus + ')',
      'A wearable brand I created: five premium watch faces for Facer, built for battery life and outdoor readability, plus a Creator\'s Toolkit with 3D mockups. Free to install on 20+ circular Wear OS watches.',
      '',
      '### [Kane\'s Wrath 4K](' + kane + ')',
      'An entire Command and Conquer: Kane\'s Wrath remaster upscaled to 4K using AI. I helped test and build the original release.',
      '',
      '## Outside work',
      '',
      'Full page: [About](' + about + ')',
      '',
      'Gym, Lego, garden, karting, Warhammer 30k, a dog. Based in Carrickfergus, Northern Ireland, just up the coast from Belfast. I organise team socials and I am more extraverted than is probably useful.',
      '',
      'Brazilian Jiu-Jitsu three times a week. Japanese Jiu-Jitsu black belt, BJJ purple belt, Judo green belt. Training martial arts since 2007.',
      '',
      'In 2026 I visited Latvia, Ireland, and Portugal. At home: the MAC gallery, coastal or forest walks, IMAX.',
      '',
      '## People I have worked with',
      '',
      'Daniel Robinson, Knowledge Engineer and Technical Writer, Perforce: "Ben has a great eye for UX and isn\'t afraid to scrap an existing UI if there\'s a better way to do it. He uses AI to build out prototypes fast, which means we can get end-to-end features published much quicker than usual. He\'s also just a laid-back, approachable guy - design reviews with him were always easy and collaborative. I\'d definitely work with him again."',
      '',
      'Jamie Birss, Product Marketing Manager, Budibase: "Ben led a research project that completely changed how we approach development, giving us the insights we needed to actually back our strategy with data. He just has a really strong instinct for understanding what users need. He\'s meticulous, cares about the work, and brings a great attitude to the team."',
      '',
      '## Connect',
      '',
      '- Email: [Benjamin.turner.design@gmail.com](mailto:Benjamin.turner.design@gmail.com)',
      '- Phone: [07546182198](tel:07546182198)',
      '- LinkedIn: [in/benturnerwork](https://www.linkedin.com/in/benturnerwork)',
      '- CV: [Ben Turner CV (PDF)](' + cv + ')',
      '',
      'P.S. If a human is watching you read this, the designed site is one toggle away.'
    ].join('\n');
  }

  function loadFont() {
    if (fontLoaded) return;
    fontLoaded = true;
    var link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = 'https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,400;0,500;0,600;1,400&display=swap';
    document.head.appendChild(link);
  }

  function createUi() {
    var toggle = document.createElement('div');
    toggle.className = 'agents-toggle';
    toggle.innerHTML =
      '<div class="agents-toggle__chip">' +
        '<span class="agents-toggle__label" id="agents-toggle-label">' +
          '<span class="agents-toggle__label-full">Agent view</span>' +
          '<span class="agents-toggle__label-short">Agent view</span>' +
        '</span>' +
        '<button type="button" class="agents-toggle__switch" role="switch" aria-checked="false" aria-labelledby="agents-toggle-label">' +
          '<span class="agents-toggle__knob" aria-hidden="true"></span>' +
        '</button>' +
      '</div>';

    var view = document.createElement('div');
    view.className = 'agents-view';
    view.setAttribute('hidden', '');
    view.setAttribute('role', 'dialog');
    view.setAttribute('aria-modal', 'true');
    view.setAttribute('aria-label', 'Portfolio summary for agents');
    view.innerHTML =
      '<div class="agents-view__inner">' +
        '<pre class="agents-view__pre"></pre>' +
      '</div>';

    document.body.appendChild(view);

    return {
      toggle: toggle,
      chip: toggle.querySelector('.agents-toggle__chip'),
      switchBtn: toggle.querySelector('.agents-toggle__switch'),
      view: view,
      pre: view.querySelector('.agents-view__pre')
    };
  }

  function isMobileNav() {
    return window.matchMedia('(max-width: 768px)').matches;
  }

  function mountToggle(ui) {
    var navContainer = document.querySelector('.nav-container');
    var inNav = isMobileNav() && navContainer;

    ui.toggle.classList.toggle('agents-toggle--in-nav', inNav);

    if (inNav) {
      if (ui.toggle.parentNode !== navContainer) navContainer.appendChild(ui.toggle);
    } else if (ui.toggle.parentNode !== document.body) {
      document.body.appendChild(ui.toggle);
    }
  }

  function setEnabled(ui, enabled, persist) {
    document.body.classList.toggle('is-agents-view', enabled);
    ui.switchBtn.setAttribute('aria-checked', enabled ? 'true' : 'false');

    if (enabled) {
      loadFont();
      ui.pre.textContent = markdownSource();
      ui.view.removeAttribute('hidden');
      window.scrollTo(0, 0);
    } else {
      ui.view.setAttribute('hidden', '');
    }

    mountToggle(ui);

    if (persist) {
      try {
        if (enabled) localStorage.setItem(STORAGE_KEY, '1');
        else localStorage.removeItem(STORAGE_KEY);
      } catch (err) {}
    }
  }

  function init() {
    var ui = createUi();
    loadFont();
    var saved = false;
    try {
      saved = localStorage.getItem(STORAGE_KEY) === '1';
    } catch (err) {}

    setEnabled(ui, saved, false);

    ui.switchBtn.addEventListener('click', function () {
      setEnabled(ui, !document.body.classList.contains('is-agents-view'), true);
    });

    ui.chip.addEventListener('click', function (event) {
      if (event.target.closest('.agents-toggle__switch')) return;
      ui.switchBtn.click();
    });

    document.querySelectorAll('.nav-group .nav-item').forEach(function (link) {
      link.addEventListener('click', function () {
        if (!document.body.classList.contains('is-agents-view')) return;
        try {
          localStorage.removeItem(STORAGE_KEY);
        } catch (err) {}
        // Clear persisted state only — don't unmount the view before navigation,
        // or the designed site flashes underneath for a frame.
      });
    });

    window.addEventListener('resize', function () {
      mountToggle(ui);
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
